errors:
  - vadimvoronezh@yandex.ru
alerts:
  suppress:
    - on-found-puzzle
    - on-lost-puzzle
    - on-scope
  github:
    - vryazanov
format:
  - short-title
  - title-length=100
tags:
  - pdd
  - bug